<a href="https://colab.research.google.com/github/LLewis/ai-deep-learning-lewis-practice/blob/main/1P_LewisTransposeMatrix_Vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The transpose of a matrix is found by interchanging its rows into columns or columns into rows. The transpose of the matrix is denoted by using the letter “T” in the superscript of the given matrix. For example, if “A” is the given matrix, then the transpose of the matrix is represented by A' or AT.
https://byjus.com/maths/transpose-of-a-matrix/

In [95]:
#import libraries
import torch
import numpy as np

# warm-up numpy one row vector
"""
onerowvector = np.array([1,2,3,4,5,6,7,8,9])
for element in onerowvector:
  print('nunpy array:' , element)
print(onerowvector), print()

#pytorch tensor - like a list or array
newtensor = torch.Tensor([6,7,8])
print('new tensor: ' , newtensor)
"""
#***USING NUMPY np.array([])*****an ndarray() type******************************
#--------WORKING WITH VECTORS-------------------------------
#create a row vector using numpy array
newrowvector = np.array([[1,2,3,4,5,6,7,8,9,10]])
print('new one row vector:', newrowvector),print('')

#Transpose row vector to a column vector
transposedvector = newrowvector.T
print('the newrowvector transposed to column vector by using the numpy function T for transpose')
print(transposedvector),print('')

#transpose vector back to original row vector
transposedvectorT = transposedvector.T
print('transpose the transposed: -vector transposed back to orginal row vector')
print(transposedvectorT)

new one row vector: [[ 1  2  3  4  5  6  7  8  9 10]]

the newrowvector transposed to column vector by using the numpy function T for transpose
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]

transpose the transposed: -vector transposed back to orginal row vector
[[ 1  2  3  4  5  6  7  8  9 10]]


In [96]:
#***USING NUMPY np.array([]) an ndarray() type**********************************
#----------WORKING WITH MATRIX---------------------------
#create a matrix with 3 rows and 4 columns using numpy
newmatrix = np.array([[11,12,13,14],[15,16,17,18],[19,20,21,22]])
print('new matrix 3x4:')
print(newmatrix)

#Transpose matrix using the numpy T transpose function
newmatrixT = newmatrix.T
print('transposed matrix, now 4x3')
print(newmatrixT)

#transpose the transposed
transposedmatrixT = newmatrixT.T
print('transpose the transposed matrix back to original 3x4')
print(transposedmatrixT)

new matrix 3x4:
[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]
transposed matrix, now 4x3
[[11 15 19]
 [12 16 20]
 [13 17 21]
 [14 18 22]]
transpose the transposed matrix back to original 3x4
[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]


In [97]:
#***USING PYTORCH torch.tensor([])*****using torch.Tensor class****************************************************
#--------WORKING WITH VECTORS-------------------------------
#create a tensor row vector- can also add additional rows by implementing- torch.tensor([[1,2,3,4,5],[6,7,8,9,10]]

tensorrowvector = torch.tensor([[1,2,3,4,5]])
print('tensor row vector')
print(tensorrowvector)

#transpose to tensor column vector
tensorrowvectorT = tensorrowvector.T
print('transposed to tensor column vector ')
print(tensorrowvectorT)

#tranpose the transposed
transposedvectorbackT = tensorrowvectorT.T
print('transpose back to tensor row vector')
print(transposedvectorbackT)

tensor row vector
tensor([[1, 2, 3, 4, 5]])
transposed to tensor column vector 
tensor([[1],
        [2],
        [3],
        [4],
        [5]])
transpose back to tensor row vector
tensor([[1, 2, 3, 4, 5]])


In [98]:
#***USING PYTORCH torch.tensor([])*****uses torch.Tensor****************************************************
#--------WORKING WITH MATRIX-------------------------------
#create a matix using pytorh's torch.tensor
pytorchmatrix = torch.tensor([[20,21,22,23],[24,25,26,27],[28,29,30,31]])
print('matrix 3x4 using pytorch torch.tensor')
print(pytorchmatrix)

#transpose matrix to 4x3
pytorchmatrixT = pytorchmatrix.T
print('transposed matrix now 4x3')
print(pytorchmatrixT)

#transpose the transposed matrix back to original 3x4
transposedmatrixbackT = pytorchmatrixT.T
print('transpose the transposed matrix back to original 3x4')
print(transposedmatrixbackT)

matrix 3x4 using pytorch torch.tensor
tensor([[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]])
transposed matrix now 4x3
tensor([[20, 24, 28],
        [21, 25, 29],
        [22, 26, 30],
        [23, 27, 31]])
transpose the transposed matrix back to original 3x4
tensor([[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]])


In [99]:
print(f'Variable newrowvector is of type {type(newrowvector)}')
print(f'Variable transposedvectorT is of type {type(transposedvectorT)}')
print(f'Variable newmatrix is of type {type(newmatrix)}')
print(f'Variable newmatrixT is of type {type(newmatrixT)}')

print(f'Variable tensorrowvector is of type {type(tensorrowvector)}')
print(f'Variable tensorrowvectorT is of type {type(tensorrowvectorT)}')
print(f'Variable pytorchmatrix is of type {type(pytorchmatrix)}')
print(f'Variable pytorchmatrixT is of type {type(pytorchmatrixT)}')

Variable newrowvector is of type <class 'numpy.ndarray'>
Variable transposedvectorT is of type <class 'numpy.ndarray'>
Variable newmatrix is of type <class 'numpy.ndarray'>
Variable newmatrixT is of type <class 'numpy.ndarray'>
Variable tensorrowvector is of type <class 'torch.Tensor'>
Variable tensorrowvectorT is of type <class 'torch.Tensor'>
Variable pytorchmatrix is of type <class 'torch.Tensor'>
Variable pytorchmatrixT is of type <class 'torch.Tensor'>
